const animalArray = [
  {
    aCate: "고양이",
    aidx: 0,
    aName: "콩이",
    aAge: "4살",
    aGender: "남",
    aSur: true,
    aChar: "콩이는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "anna-BSWeh_sSh7I-unsplash.jpg",
    aWeight: 3.8,
    aKind: "코리아숏헤어",
    aLocation: "대전시 유성구 작은숨 보호소",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 완료"
  },
  {
    aCate: "고양이",
    aidx: 1,
    aName: "두부",
    aAge: "4살",
    aGender: "여",
    aSur: true,
    aChar: "두부는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "anna-w5iimOQlr5c-unsplash.jpg",
    aWeight: 3.8,
    aKind: "스코티시폴드",
    aLocation: "인천시 서구 반려동물센터",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 대기"
  },
  {
    aCate: "고양이",
    aidx: 2,
    aName: "보리",
    aAge: "5살",
    aGender: "남",
    aSur: true,
    aChar: "보리는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "daria-averina-_867Jy8LCkI-unsplash.jpg",
    aWeight: 5.2,
    aKind: "먼치킨",
    aLocation: "광주시 북구 따뜻한보호소",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 가능"
  },
  {
    aCate: "고양이",
    aidx: 3,
    aName: "치즈",
    aAge: "5살",
    aGender: "남",
    aSur: true,
    aChar: "치즈는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "kabo-p6yH8VmGqxo-unsplash.jpg",
    aWeight: 3.4,
    aKind: "메인쿤",
    aLocation: "경기도 성남시 분당구 미금동 123-1번지 하이테크그린 보호소 미금점",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 완료"
  },
  {
    aCate: "고양이",
    aidx: 4,
    aName: "초코",
    aAge: "3살",
    aGender: "여",
    aSur: true,
    aChar: "초코는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "mikhail-vasilyev-IFxjDdqK_0U-unsplash.jpg",
    aWeight: 5.0,
    aKind: "샴",
    aLocation: "대전시 유성구 작은숨 보호소",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 대기"
  },
  {
    aCate: "고양이",
    aidx: 5,
    aName: "밤이",
    aAge: "3살",
    aGender: "여",
    aSur: true,
    aChar: "밤이는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "mona-magnussen-a7bdqjeG6M4-unsplash.jpg",
    aWeight: 4.4,
    aKind: "스코티시폴드",
    aLocation: "광주시 북구 따뜻한보호소",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 가능"
  },
  {
    aCate: "고양이",
    aidx: 6,
    aName: "달이",
    aAge: "3살",
    aGender: "여",
    aSur: true,
    aChar: "달이는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "istockphoto-2196096412-612x612.webp",
    aWeight: 5.9,
    aKind: "노르웨이숲",
    aLocation: "광주시 북구 따뜻한보호소",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 가능"
  },
  {
    aCate: "고양이",
    aidx: 7,
    aName: "누리",
    aAge: "2살",
    aGender: "여",
    aSur: true,
    aChar: "누리는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "matthew-henry-2Ts5HnA67k8-unsplash.jpg",
    aWeight: 5.2,
    aKind: "샴",
    aLocation: "대구시 동구 희망센터",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 대기"
  },
  {
    aCate: "고양이",
    aidx: 8,
    aName: "하늘",
    aAge: "4살",
    aGender: "남",
    aSur: true,
    aChar: "하늘는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "ludemeula-fernandes-9UUoGaaHtNE-unsplash.jpg",
    aWeight: 4.8,
    aKind: "페르시안",
    aLocation: "서울시 강동구 반려동물 보호센터",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 대기"
  },
  {
    aCate: "고양이",
    aidx: 9,
    aName: "별이",
    aAge: "4살",
    aGender: "여",
    aSur: true,
    aChar: "별이는 사람을 좋아하지만 처음에는 조금 수줍어해요. 시간이 지나면 애교가 많아져서 옆에 꼭 붙어 있는 걸 좋아한답니다.",
    aThumb: "mona-magnussen-a7bdqjeG6M4-unsplash.jpg",
    aWeight: 3.3,
    aKind: "메인쿤",
    aLocation: "대구시 동구 희망센터",
    aStateHealth: "기초 접종과 중성화 수술을 완료했으며, 최근 건강검진에서 특이사항 없이 건강하다는 소견을 받았어요.",
    aGoState: "입양 대기"
  }
]; 